### ISSUE TITLE
API definitions should not have parameters with 'Boolean' values

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucsm_apis#26]
**ucsm_apis version:** Latest code
**Python version:** 2.7.12
**Operating System:** Win 10

**Description -**

API definitions should not have parameters with 'Boolean' values. Need to remove from below list of APIs -

_auth_domain_realm_configure
boot_policy_create_

**Comment by ragupta-git** [comment]
Fixed across different PRs.

**Comment by tanmayx** [comment]
Verified. Marking as closed.
