### ISSUE TITLE
When changing 'realm' to 'local', the older value of provider_group still persists

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucsm_apis#28]
**ucsm_apis version:** Latest code
**Python version:** 2.7.12
**Operating System:** Win 10

**Description**
When trying to change the domain `realm` from say `tacacs` to `local`, the older value of `provider_group` still persists. Whereas the default value of `provider_group` is passed as `None`

So a domain has realm set to `tacacs` with `provider_group='abc'`

**What I Did**
_Executed the below code -_
```
obj = auth_domain_realm_configure(handle=handle, domain_name='d_local')
```
When try to print the `obj`, the value of `provider_group` is shown as 'abc'. But as per the above command, the default value passed for `provider_group` is `None`

**Comment by ragupta-git** [comment]
Fixed in PR: Modified exists api to support multiple param set related to auth. #43

**Comment by tanmayx** [comment]
Verified. Marking as closed.
