### ISSUE TITLE
radius_provider_group_add_provider(), radius_provider_group_modify_provider(), radius_provider_group_remove_provider() API name is not correct

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucsm_apis#33]
ucsm_apis version: Latest code
Python version: 2.7.12
Operating System: Win 10

**Description -**
Below API names not correct -
`radius_provider_group_add_provider()` -> `radius_provider_group_provider_add()`
`radius_provider_group_modify_provider()` -> `radius_provider_group_provider_modify()`
`radius_provider_group_remove_provider()` -> `radius_provider_group_provider_remove()`

**Comment by ragupta-git** [comment]
Fixed in PR: modified exists api for radius config #44

**Comment by tanmayx** [comment]
Verified. Marking as closed.
