### ISSUE TITLE
user_role_add() API doe not have option to add multiple roles for a user.

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucsm_apis#35]
ucsm_apis version: Latest code
Python version: 2.7.12
Operating System: Win 10

**Description -**
Trying to add multiple roles for a single user. Currently in the `user_role_add()` API, there is no option to add multiple roles. Only single role can be added at a time.

**What I Did -**
Executed the below code which throws error
```
user_role_add(handle=handle, user_name='user1', name='network,storage,operations')
```

The code that works fine -
```
user_role_add(handle=handle, user_name='user1', name='network')
user_role_add(handle=handle, user_name='user1', name='storage')
user_role_add(handle=handle, user_name='user1', name='operations')
```

**Comment by ragupta-git** [comment]
Fixed in PR: Added exists api for password strength and profile. #41

**Comment by tanmayx** [comment]
Verified. Marking as closed.
